##### Set path for input data, output fold, run name, thread number, 
# The input sequencing file could be in .fastq or fastq.gz(compressed file)
tumor_fastq_path_first: /home/zhouchi/test/SRR2602447_1.fastq.gz
tumor_fastq_path_second: /home/zhouchi/test/SRR2602447_2.fastq.gz
normal_fastq_path_first: /home/zhouchi/test/SRR2602449_1.fastq.gz
normal_fastq_path_second: /home/zhouchi/test/SRR2602449_2.fastq.gz
tumor_rna_fastq_1: /home/zhouchi/test/SRR2603944_1.fastq.gz
tumor_rna_fastq_2: /home/zhouchi/test/SRR2603944_2.fastq.gz
# Output directory, it could be in absolute path (eg: /home/test)or relative path(eg: test/).
output_fold: WES_test
# Sample name for your run
sample_name: WES_test
# Thread number for running, set it based on your system and your requirement.
thread_number: 64
# Set hla allele for neoantigen identification, separated by comma and up to six hla type eg:HLA-A02:01,HLA-A24:02,HLA-B44:02,HLA-B15:01,HLA-C05:01,HLA-C07:02
# If set to None, hla typing process would be run automatically.
hla_str: None
# Expression profile, format described in mannual, if your provide tumor RNA-seq sequencing data, pTuneos would do it using Kallisto automatically.
expression_file: None
# Set neoantigen peptide length, separatd by comma, eg: 9,10,11.
peptide_length: 9,10,11
# Keep temporal file (0 means no and 1 means yes, default: 0).
tmp: 1
# Specify genome version, could be hg38 or hg19.
genome_version: hg19
# Fragment length of RNA-seq data (not read length), typical value for RNA-seq is 200. (This parameter is for single-end RNA-seq)
fragment_length: 200
# Standard deviation of fragment length of RNA-seq data (not read length), typical value for RNA-seq is 30. (This parameter is for single-end RNA-seq)
fragment_SD: 30

##### Some filters parameter
#Minimal read depth for altenative allele
tumor_depth_cutoff: 7
#Minimal variant allele frequency for altenative allele
tumor_vaf_cutoff: 0.05
#Minimal variant allele frequency for reference allele
normal_vaf_cutoff: 0.03
# Fold change between MHC-mutant-peptide-binding-affinity and MHC-normal-peptide-binding-affinity, 1 means they are equal.
binding_fc_aff_cutoff: 1
# MHC-mutant-peptide binding affinity rank cutoff, usually set to 2.
binding_aff_cutoff: 2
# Expression value cutoff of neo-peptide, usually set to 1.
fpkm_cutoff: 0


##### specify other software excutable path in your system as you have installed them, make sure each tools could run.
opitype_fold: /home/zhouchi/software/OptiType/OptiTypePipeline.py
vep_cache_path: /home/zhouchi/test_data/pTuneos/vep_data
vep_path: /home/zhouchi/software/ensembl-vep/vep
netMHCpan_path: /home/zhouchi/software/netMHCpan-4.0/netMHCpan
pyclone_path: /usr/local/bin/PyClone
sequenza_path: /usr/local/bin/sequenza-utils
